seed: 42
cuda: true

model:
  arch: unet
  config:
    in_channels: 3
    out_channels: 3

train:
  learning_rate: 1e-4
  optimizer: Adam
  scheduler: None
  max_epoches: 100
  validation_step: 500
  checkpoint_step: 20000
  max_train_steps: 100000

data:
  name: CIFAR10
  batch_size: 64
  num_workers: 6
